eureka:
  client:
    service-url:
      defaultZone: http://peer1:9099/eureka/

zuul:
  #ignored-services: microservice-provider-user        # 需要忽视的服务(配置后将不会被路由)
  routes:
    spring-cloud-user-service:                         # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                   # 映射的url
      service-id: spring-cloud-user-service            # Eureka中的serviceId
    spring-cloud-order-service:                        # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /order/**                                  # 想要映射到的路径
      service-id: spring-cloud-order-service           # Eureka中的serviceId
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000

logging:
  level:
    com.netflix: debug