spring:
  application:
   name: spring-cloud-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: spring-cloud-gateway-zuul
server:
  port: 9056
zuul:
  #ignored-services: microservice-provider-user          # 需要忽视的服务(配置后将不会被路由)
  routes:
    api-a:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                   # 想要映射到的路径
      service-id: spring-cloud-user-service    # Eureka中的serviceId
    api-b:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /order/**                                   # 想要映射到的路径
      service-id: spring-cloud-order-service    # Eureka中的serviceId
  ribbon:  
    ReadTimeout: 60000  
    ConnectTimeout: 60000   