spring:
  application:
   name: spring-cloud-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka/
server:
  port: 9056
zuul:
  #ignored-services: microservice-provider-user          # 需要忽视的服务(配置后将不会被路由)
  routes:
    api-a:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /test/**                                   # 想要映射到的路径
      service-id: spring-cloud-service    # Eureka中的serviceId
  ribbon:  
    ReadTimeout: 60000  
    ConnectTimeout: 60000   